apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: webserver
spec:
  replicas: 3
  selector:
    matchLabels:
      service: nginxweb
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        service: nginxweb
    spec:
      containers:
      - name: web
        image: vipin2411/nginx-alpine:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80

