apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: webserver-rs
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx-web
  template:
    metadata:
     labels:
       app: nginx-web
       env: devlopment
    spec:
     containers:
       - name: web
         image: nginx:1.16-alpine
