apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
spec:
  minReadySeconds: 10
  progessDeadlineSeconds: 300
  revisionHistoryLimit: 3
  replicas: 3
  selector: 
    matchLabels:
      app: nginxweb
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nginxweb
        type: production
        ver: v1
    spec:
      containers:
      - images: vipin2411/nginx-alpine:v1
        name: web
        ports:
        - contianerPort: 80
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /
            Port: 80
        initialDeploySeconds: 30
        timeoutSeconds: 10
        periodSeconds: 5
        successThreshold: 1
        failureThreshold: 2
    restartPolicy: Always 
